# Generated by Django 5.1.2 on 2024-10-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
