# Generated by Django 5.1.2 on 2024-10-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=100)),
                ('ubicacion_sede', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('apellido_medico', models.CharField(max_length=100)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidades')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sedes')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicos')),
            ],
        ),
    ]
